################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
vlc2/test/src/misc \
vlc2/test/src/input \
vlc2/test/src/crypto \
vlc2/test/src/config \
vlc2/test/native \
vlc2/test/libvlc \
vlc2/test/dynamicoverlay \
vlc2/src/win32 \
vlc2/src/video_output \
vlc2/src/video_output/.libs \
vlc2/src \
vlc2/src/text \
vlc2/src/text/.libs \
vlc2/src/test \
vlc2/src/stream_output \
vlc2/src/stream_output/.libs \
vlc2/src/posix \
vlc2/src/posix/.libs \
vlc2/src/playlist \
vlc2/src/playlist/.libs \
vlc2/src/os2 \
vlc2/src/network \
vlc2/src/network/.libs \
vlc2/src/modules \
vlc2/src/modules/.libs \
vlc2/src/misc \
vlc2/src/misc/.libs \
vlc2/src/interface \
vlc2/src/interface/.libs \
vlc2/src/input \
vlc2/src/input/.libs \
vlc2/src/extras \
vlc2/src/extras/.libs \
vlc2/src/darwin \
vlc2/src/config \
vlc2/src/config/.libs \
vlc2/src/audio_output \
vlc2/src/audio_output/.libs \
vlc2/src/android \
vlc2/src/.libs \
vlc2/modules/visualization/visual \
vlc2/modules/visualization/visual/.libs \
vlc2/modules/visualization \
vlc2/modules/visualization/.libs \
vlc2/modules/video_splitter \
vlc2/modules/video_splitter/.libs \
vlc2/modules/video_output \
vlc2/modules/video_output/xcb \
vlc2/modules/video_output/xcb/.libs \
vlc2/modules/video_output/wayland \
vlc2/modules/video_output/msw \
vlc2/modules/video_output/android \
vlc2/modules/video_output/.libs \
vlc2/modules/video_filter \
vlc2/modules/video_filter/dynamicoverlay \
vlc2/modules/video_filter/dynamicoverlay/.libs \
vlc2/modules/video_filter/deinterlace \
vlc2/modules/video_filter/deinterlace/.libs \
vlc2/modules/video_filter/.libs \
vlc2/modules/video_chroma \
vlc2/modules/video_chroma/.libs \
vlc2/modules/text_renderer \
vlc2/modules/text_renderer/fonts \
vlc2/modules/text_renderer/fonts/.libs \
vlc2/modules/text_renderer/.libs \
vlc2/modules/stream_out \
vlc2/modules/stream_out/transcode \
vlc2/modules/stream_out/transcode/.libs \
vlc2/modules/stream_out/.libs \
vlc2/modules/stream_filter \
vlc2/modules/stream_filter/hds \
vlc2/modules/stream_filter/hds/.libs \
vlc2/modules/stream_filter/.libs \
vlc2/modules/services_discovery \
vlc2/modules/services_discovery/.libs \
vlc2/modules/packetizer \
vlc2/modules/packetizer/.libs \
vlc2/modules/notify \
vlc2/modules/notify/.libs \
vlc2/modules/mux \
vlc2/modules/mux/mpeg \
vlc2/modules/mux/mpeg/.libs \
vlc2/modules/mux/mp4 \
vlc2/modules/mux/mp4/.libs \
vlc2/modules/mux/.libs \
vlc2/modules/misc/xml \
vlc2/modules/misc/xml/.libs \
vlc2/modules/misc/webservices \
vlc2/modules/misc/webservices/.libs \
vlc2/modules/misc \
vlc2/modules/misc/playlist \
vlc2/modules/misc/playlist/.libs \
vlc2/modules/misc/inhibit \
vlc2/modules/misc/inhibit/.libs \
vlc2/modules/misc/addons \
vlc2/modules/misc/addons/.libs \
vlc2/modules/misc/.libs \
vlc2/modules/meta_engine \
vlc2/modules/meta_engine/.libs \
vlc2/modules/lua \
vlc2/modules/lua/libs \
vlc2/modules/lua/libs/.libs \
vlc2/modules/lua/.libs \
vlc2/modules/logger \
vlc2/modules/logger/.libs \
vlc2/modules/hw/vdpau \
vlc2/modules/hw/mmal \
vlc2/modules/gui/skins2/x11/.libs \
vlc2/modules/gui/skins2/vars/.libs \
vlc2/modules/gui/skins2/utils/.libs \
vlc2/modules/gui/skins2/src \
vlc2/modules/gui/skins2/src/.libs \
vlc2/modules/gui/skins2/parser/.libs \
vlc2/modules/gui/skins2/events/.libs \
vlc2/modules/gui/skins2/controls/.libs \
vlc2/modules/gui/skins2/commands/.libs \
vlc2/modules/gui/qt4/util/buttons/.libs \
vlc2/modules/gui/qt4/util/.libs \
vlc2/modules/gui/qt4/styles/.libs \
vlc2/modules/gui/qt4/managers/.libs \
vlc2/modules/gui/qt4/dialogs/.libs \
vlc2/modules/gui/qt4/components/sout/.libs \
vlc2/modules/gui/qt4/components/playlist/.libs \
vlc2/modules/gui/qt4/components/epg/.libs \
vlc2/modules/gui/qt4/components/.libs \
vlc2/modules/gui/qt4/adapters/.libs \
vlc2/modules/gui/qt4/.libs \
vlc2/modules/gui \
vlc2/modules/gui/minimal_macosx \
vlc2/modules/gui/.libs \
vlc2/modules/demux \
vlc2/modules/demux/smooth/playlist/.libs \
vlc2/modules/demux/smooth/mp4/.libs \
vlc2/modules/demux/smooth/.libs \
vlc2/modules/demux/playlist \
vlc2/modules/demux/playlist/.libs \
vlc2/modules/demux/mpeg \
vlc2/modules/demux/mpeg/.libs \
vlc2/modules/demux/mp4 \
vlc2/modules/demux/mp4/.libs \
vlc2/modules/demux/mkv/.libs \
vlc2/modules/demux/hls/playlist/.libs \
vlc2/modules/demux/hls/.libs \
vlc2/modules/demux/dash/mpd/.libs \
vlc2/modules/demux/dash/mp4/.libs \
vlc2/modules/demux/dash/.libs \
vlc2/modules/demux/avi \
vlc2/modules/demux/avi/.libs \
vlc2/modules/demux/avformat \
vlc2/modules/demux/asf \
vlc2/modules/demux/asf/.libs \
vlc2/modules/demux/adaptative/xml/.libs \
vlc2/modules/demux/adaptative/tools/.libs \
vlc2/modules/demux/adaptative/plumbing/.libs \
vlc2/modules/demux/adaptative/playlist/.libs \
vlc2/modules/demux/adaptative/mp4/.libs \
vlc2/modules/demux/adaptative/logic/.libs \
vlc2/modules/demux/adaptative/http/.libs \
vlc2/modules/demux/adaptative/.libs \
vlc2/modules/demux/.libs \
vlc2/modules/control \
vlc2/modules/control/globalhotkeys \
vlc2/modules/control/globalhotkeys/.libs \
vlc2/modules/control/dbus \
vlc2/modules/control/dbus/.libs \
vlc2/modules/control/.libs \
vlc2/modules/codec \
vlc2/modules/codec/wmafixed \
vlc2/modules/codec/spudec \
vlc2/modules/codec/spudec/.libs \
vlc2/modules/codec/omxil \
vlc2/modules/codec/dmo \
vlc2/modules/codec/avcodec \
vlc2/modules/codec/avcodec/.libs \
vlc2/modules/codec/arib \
vlc2/modules/codec/arib/.libs \
vlc2/modules/codec/.libs \
vlc2/modules/audio_output \
vlc2/modules/audio_output/.libs \
vlc2/modules/audio_mixer \
vlc2/modules/audio_mixer/.libs \
vlc2/modules/audio_filter \
vlc2/modules/audio_filter/spatializer \
vlc2/modules/audio_filter/spatializer/.libs \
vlc2/modules/audio_filter/resampler \
vlc2/modules/audio_filter/resampler/.libs \
vlc2/modules/audio_filter/converter \
vlc2/modules/audio_filter/converter/.libs \
vlc2/modules/audio_filter/channel_mixer \
vlc2/modules/audio_filter/channel_mixer/.libs \
vlc2/modules/audio_filter/.libs \
vlc2/modules/arm_neon \
vlc2/modules/access_output \
vlc2/modules/access_output/.libs \
vlc2/modules/access/zip \
vlc2/modules/access/zip/unzip \
vlc2/modules/access/zip/unzip/.libs \
vlc2/modules/access/zip/.libs \
vlc2/modules/access \
vlc2/modules/access/vcdx \
vlc2/modules/access/vcd \
vlc2/modules/access/vcd/.libs \
vlc2/modules/access/v4l2 \
vlc2/modules/access/v4l2/.libs \
vlc2/modules/access/screen \
vlc2/modules/access/screen/.libs \
vlc2/modules/access/rtsp \
vlc2/modules/access/rtp \
vlc2/modules/access/rtp/.libs \
vlc2/modules/access/rar \
vlc2/modules/access/rar/.libs \
vlc2/modules/access/mms \
vlc2/modules/access/mms/.libs \
vlc2/modules/access/linsys \
vlc2/modules/access/linsys/.libs \
vlc2/modules/access/dvb \
vlc2/modules/access/dvb/.libs \
vlc2/modules/access/dtv \
vlc2/modules/access/dtv/.libs \
vlc2/modules/access/dsm \
vlc2/modules/access/bd \
vlc2/modules/access/bd/.libs \
vlc2/modules/access/archive \
vlc2/modules/access/.libs \
vlc2/modules/.libs \
vlc2/lib \
vlc2/lib/.libs \
vlc2/extras/package/win32/NSIS/nsProcess \
vlc2/extras/package/macosx/eyetvplugin \
vlc2/doc/libvlc \
vlc2/contrib/native/aribb25/src \
vlc2/contrib/native/aribb24/src \
vlc2/contrib/native/a52dec/test \
vlc2/contrib/native/a52dec/src \
vlc2/contrib/native/a52dec/libao \
vlc2/contrib/native/a52dec/liba52 \
vlc2/compat \
vlc2/compat/.libs \
vlc2/bin \
vlc2/.metadata/.plugins/org.eclipse.cdt.make.core \

